### ISSUE TITLE
Collection upgrade not working

### ISSUE THREAD

**Issue by AnderUstarroz** [metaplex-foundation/mip#2]
I have tried to [upgrade](https://royalties.metaplex.com/migrate) the following collection:

https://explorer.solana.com/address/4fMFhKArCxFaPvNaw5QEtqkKcXnBhMd8Yxo4QQRLGfxq

But throws an error that does not make much sense to me:

<img width="1128" alt="Screenshot 2023-01-14 at 12 44 29" src="https://user-images.githubusercontent.com/8544110/212446600-1b05564a-789b-49dd-ac7a-f7d991eaf93e.png">

As you can see on the link above the collection is mutable but still fails.
The collection only contains [these 5 items](https://solscan.io/collection/297e1c1f6f0ee85d5066b3aea8fa26bf142f7a660c9fd4e8dcb22bf33caccd81).

**Comment by samuelvanderwaal** [comment]
Your collection is set up correctly on-chain but is not being picked up by the indexer we are using for some reason. We're looking at other indexers and possibly just letting users supply the mint list as a fallback solution. 

In the meantime, if you are technically inclined, there's a [CLI](https://github.com/metaplex-foundation/goose) you can use to set up the migration state account start the clock, or you can wait until the UI is fixed.

**Comment by AnderUstarroz** [comment]
We can wait, but is there any ETA for the swapt to a new indexer? Or can I know where or how will you publish the update?

**Comment by samuelvanderwaal** [comment]
> We can wait, but is there any ETA for the swapt to a new indexer? Or can I know where or how will you publish the update?

I also pinged the indexer so they might get this particular collection fixed. I would try again in a day or two and if I have any updates I'll post to this issue.

**Comment by itsmodsiw** [comment]
For some reason our timer expired but we are unable to do anything. Or have any further instructions. 

![image](https://user-images.githubusercontent.com/29111227/214000474-c918d8ef-f468-472b-8083-64a8ed97e4c0.png)

Also for some reason our collection item count is off. I assume ui/bug.

Cardboard Citizens.
5iwFavPxXKvnSoyPWHzYB6F5EfbvQq6U3jrS7GXUs3EA <-- our collection_id.

**Comment by Tomvkgames** [comment]
In our case we just upgraded to MCC, and the indexer is very slow (but working). 50 items per day are indexed. Can someone tell us when indexer will be fixed? So we can decided whether to use the CLI samuel linked.

**Comment by AnderUstarroz** [comment]
After 3 weeks the problem persists on collection:

https://explorer.solana.com/address/4fMFhKArCxFaPvNaw5QEtqkKcXnBhMd8Yxo4QQRLGfxq

No updates from Metaplex?

**Comment by urbentom** [comment]
Heya, at the moment we are waiting for ecosystem adoption of pNFTs, you can check [this tweet](https://twitter.com/metaplex/status/1618995668399575040) for more details. This is when the royalties app will allow you to upgrade your collection. So keep an eye on the [official Metaplex twitter](https://twitter.com/metaplex).

As for the supply count, we had an issue with out Indexer, but this is nothing to worry about for this stage. In the next release we have swapped out our indexer and have fallbacks in place to ensure everything is correct for when you try to complete the upgrade.

**Comment by urbentom** [comment]
Heya @Tomvkgames the indexer issue will be fixed in the next release which should be for Feb 6th. You can start the upgrade process without the correct supply ( as long as it's above 1 ).

**Comment by AnderUstarroz** [comment]
Unfortunately collection upgrade keeps failing, just tried with the following collection [97Lk4G8jMQjSh86G6BXXCFLoJ1ySwgDr9868GZJQPEx5](https://solscan.io/token/97Lk4G8jMQjSh86G6BXXCFLoJ1ySwgDr9868GZJQPEx5) but throws  the following error even having **3.18SOL** in my wallet:

![image](https://user-images.githubusercontent.com/8544110/218290306-f32a3c19-cb33-460f-8707-84480c8ecfd8.png)

**Comment by samuelvanderwaal** [comment]
@AnderUstarroz has this issue been resolved now?

**Comment by AnderUstarroz** [comment]
This problem was solved already but still not able to upgrade the collection for a different reason. It is better explained [in this issue](https://github.com/metaplex-foundation/mip/issues/3), so I guess It's ok to close this one.
