### ISSUE TITLE
Collection Upgrade : NFT aren't elegible

### ISSUE THREAD

**Issue by itsmodsiw** [metaplex-foundation/mip#3]
Greetings, so on our first issue your team look up into it as our collection was not showing up as upgrade on the right update authority, This was corrected by your team.

Former prompt **( FIXED )**

![image](https://user-images.githubusercontent.com/29111227/218304715-b4ef89f0-85a9-411b-b4c5-b4e1c43e0435.png)

#############################

**Now we encounter the following :**

Loom video of upgrading details during the issue:
https://www.loom.com/share/c6861eefdb184f4bb8700bbdef02b181

Details : Cardboard Citizens NFT Collection.

Update Authority.
AxVR1S5Wzp74YfzDYespasU5cgjjemR33uMsaQF2Tp7H

Collection ID:
5iwFavPxXKvnSoyPWHzYB6F5EfbvQq6U3jrS7GXUs3EA

Collection Update Authority is AxVR.
Collection ID Authority is on AxVR, and AxVR Holds the Collection_ID Token also.
Collection ID has never been integrated into staking or anything.
Collection was Minted in Magic Eden, and It has been working properly and verified since the start.

We get an error at the end and we don't know how to proceed.

![image](https://user-images.githubusercontent.com/29111227/218304505-500961d9-16c2-445e-896e-36e648659871.png)

![image](https://user-images.githubusercontent.com/29111227/218304528-f256c6ea-021e-479b-9a77-28923118bddb.png)

![image](https://user-images.githubusercontent.com/29111227/218304550-6f8e3acd-cecf-4f8e-84a7-0ebdc8f39181.png)

![image](https://user-images.githubusercontent.com/29111227/218304585-e3ba1a76-c373-42f6-8803-5239139836c1.png)

![image](https://user-images.githubusercontent.com/29111227/218304993-6a505736-ad55-4472-a12b-0a105d7e6474.png)

(No console error or anything we could identify).

Considering the last msg is a bit disruptive and not coherent with the objective. I would like to know how can I proceed given this fault. Or should I just continue upgrading the collection ID and then add the tokens to the Collection?

Please provide me with instructions or anything to move forward or iterate.

Best regards, Cz Team

**Comment by AnderUstarroz** [comment]
Same problem with the following collection [97Lk4G8jMQjSh86G6BXXCFLoJ1ySwgDr9868GZJQPEx5](https://solscan.io/token/97Lk4G8jMQjSh86G6BXXCFLoJ1ySwgDr9868GZJQPEx5) 

![image](https://user-images.githubusercontent.com/8544110/218306794-91021c49-fa18-4863-bf21-48ade495ea12.png)

**Comment by MarkSackerberg** [comment]
Hey,
thanks for reporting.
Both of your collection have the problem that your NFTs don't have a collection standard set:
![image](https://user-images.githubusercontent.com/93528482/218307381-17b407db-be51-4534-aa7f-01b689bace8d.png)

There is someone of the team already working on a workaround. We'll let you know.

In case someone else is seeing an issue like this, check if your NFTs have the same undefined tokenStandard as shown above. In that case please check again later here or on discord.

**Comment by itsmodsiw** [comment]
Awsome, so this new "tokenStandard" item default value is 0, should we update all our tokens to 4? as stated in discord.

![image](https://user-images.githubusercontent.com/29111227/218326486-8e71cce0-210a-40df-a2c4-73f9bb58de05.png)

So just updating that metadata is enough to make them pNFT?

Thanks.

**Comment by MarkSackerberg** [comment]
Hi @itsmodsiw,
No, you can't just update them to 4.
What you can do is set them from undefined to 0, then run the migration through royalties.metaplex.com

A solution to set the tokenStandard to 0 will most likely added to metaboss in the next days. As I said, I'll let you know here.

**Comment by itsmodsiw** [comment]
Thanks, We will try it. Keep you posted.

**Comment by itsmodsiw** [comment]
It works as intended. For those who need more information. 1 hour ago an update was done to metaboss.

https://github.com/samuelvanderwaal/metaboss/releases/tag/v0.16.0

Thanks.

**Comment by AnderUstarroz** [comment]
Thanks for the update @itsmodsiw , could you confirm that this is the right solution for helping future people referring this issue:

[Update Token standard via metaboss  to all NFTs within our collection](https://metaboss.rs/set.html?highlight=Standard#set-token-standard):

```metaboss set token-standard-all --keypair <PATH_TO_KEYPAIR> --mint-list <PATH_TO_MINT_ACCOUNTS>```

**Comment by AnderUstarroz** [comment]
Token standard update failed for me:
```
 metaboss set token-standard-all --keypair /PATH_TO_MY_KEY.json  --rpc  https://MY_RPC_URL --mint-list /PATH_TO_MY_MINT_LIST.json
```
Getting:
```
Updating NFTs. . .
4998/4998 updates failed. Retrying. . .
Updating NFTs. . .
Reached max retries. Writing remaining items to cache.
Done!
```
My mint list file had the following JSON array format:   
```
[
  "7gEhwVH7hd9hBDQfuyiqRQ3vemzBAHuW6NUFoZmL28Cf",
  "7gSZkW1jN6cKZ4xPRQmyvxf2c2x9wHq69kb6dTUJFNsp",
  ...
]
```
Not a single one updated, hopefully @itsmodsiw can bring some light on this.

**Comment by samuelvanderwaal** [comment]
> Token standard update failed for me:
> 
> ```
>  metaboss set token-standard-all --keypair /PATH_TO_MY_KEY.json  --rpc  https://MY_RPC_URL --mint-list /PATH_TO_MY_MINT_LIST.json
> ```
> 
> Getting:
> 
> ```
> Updating NFTs. . .
> 4998/4998 updates failed. Retrying. . .
> Updating NFTs. . .
> Reached max retries. Writing remaining items to cache.
> Done!
> ```
> 
> My mint list file had the following JSON array format:
> 
> ```
> [
>   "7gEhwVH7hd9hBDQfuyiqRQ3vemzBAHuW6NUFoZmL28Cf",
>   "7gSZkW1jN6cKZ4xPRQmyvxf2c2x9wHq69kb6dTUJFNsp",
>   ...
> ]
> ```
> 
> Not a single one updated, hopefully @itsmodsiw can bring some light on this.

1) Are you on the right cluster? Mainnet vs devnet
2) Are you using the right update authority keypair?

Open the cache file created by the command: it will be called something like `mb-cache-set-token-standard-all` and will be in the directory you ran the command. It will give you a list of errors for why the update failed. Post some of those here.

**Comment by AnderUstarroz** [comment]
Getting the following errors @samuelvanderwaal. Both keypairs and cluster were correct, I have tried with my own paid RPC but also directly with `https://api.mainnet-beta.solana.com`, but both of them fail with same errors:

```
# file: mb-cache-set-token-standard-all

{
  "7gEhwVH7hd9hBDQfuyiqRQ3vemzBAHuW6NUFoZmL28Cf": {
    "error": "Action failed with error: AccountNotFound: pubkey=tEmfYqCPJGG6HCqWSSCtwAETHCaMkgWXsUZrPyaRvNz: error sending request for url (https://solana-mainnet.g.alchemy.com/v2/IYsd9uxVwJzwCbBrHICw-1qN73_e5erQ/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known"
  },
  "7gSZkW1jN6cKZ4xPRQmyvxf2c2x9wHq69kb6dTUJFNsp": {
    "error": "Action failed with error: AccountNotFound: pubkey=R5G45q8wuMErZbApVuSauJD8sRa6gtZP546wtHWUHnB: error sending request for url (https://solana-mainnet.g.alchemy.com/v2/IYsd9uxVwJzwCbBrHICw-1qN73_e5erQ/): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known"
  },
  
  ...
  ...
}
```

**Comment by samuelvanderwaal** [comment]
> error sending request for url (): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known

Looks like an RPC issue. That account definitely exists on chain: https://explorer.solana.com/address/tEmfYqCPJGG6HCqWSSCtwAETHCaMkgWXsUZrPyaRvNz.

**Comment by AnderUstarroz** [comment]
Yes you are right @samuelvanderwaal, it worked after trying and retrying thanks:
```
Updating NFTs. . .
3542/3719 updates failed. Retrying. . .
Updating NFTs. . .
3412/3542 updates failed. Retrying. . .
Updating NFTs. . .
3284/3412 updates failed. Retrying. . .
```
I just got 4 exceptions thought:

- [51fq6cmryZCSXuysPG4hxPg5XqZmebkBRCAbf73XgBgQ](https://explorer.solana.com/address/51fq6cmryZCSXuysPG4hxPg5XqZmebkBRCAbf73XgBgQ/metadata)
- [FwYe4r13tt19BTuDoL6oHjDSNnSBpd4R3YsKda9hkDD9](https://explorer.solana.com/address/FwYe4r13tt19BTuDoL6oHjDSNnSBpd4R3YsKda9hkDD9/metadata)
- [Dn6fzo938JPmmhTtjEQt3pADpk4PbqJGrQpVVca8qDTz](https://explorer.solana.com/address/Dn6fzo938JPmmhTtjEQt3pADpk4PbqJGrQpVVca8qDTz/metadata)
- [6329jjmx2EZha56edjus5staRxuP5FeJNcQqfikKnS2G](https://explorer.solana.com/address/6329jjmx2EZha56edjus5staRxuP5FeJNcQqfikKnS2G/metadata)

Which are throwing the following error:
```
RPC response error -32002: Transaction simulation failed: Error processing Instruction 0: custom program error: 0x6b [5 log messages]
```
[This is how a  "valid" NFT looks like](https://explorer.solana.com/address/tWmmzpPqomrga75QGviRUN6hqahi4dDRc9VT2D8RBAJ/metadata).

Do you know if there is a way to recover those 4?

**Comment by samuelvanderwaal** [comment]
For the future I recommend using [QuickNode](https://www.quicknode.com/), I have very few RPC issues with them. 

You can look up error messages with Metaboss as well:

```bash
metaboss find error 0x6b

> 	Token Metadata |	CouldNotDetermineTokenStandard: Could not determine a TokenStandard type.
```

If you look up those NFTs in the explorer you can see that they were partially burned. Someone burned the token but left the metadata and edition accounts in place so the NFT shows up but it's not a valid item any more so can't have a Token Standard set or be migrated.

**Comment by AnderUstarroz** [comment]
Thanks a lot @samuelvanderwaal you were really helpful.
