### ISSUE TITLE
Finalize NFTs to pNFT

### ISSUE THREAD

**Issue by GealeSimon89** [metaplex-foundation/mip#4]
At first we had the derive error. After we had the tokenstandard issue. 

This was fixed when we updated all our tokens to 0 value.

Now we are back into the derive error "funding" or something. 

So I think it has to be reviewed on the backend side of the derived identity 8tCgYF8Ff25KhHhjz2XYwcSqcokbg7zzQWYqdDjPRkGV

![image](https://user-images.githubusercontent.com/57489160/218999075-c432be2d-5ebf-4c46-80fb-4703564bce18.png)

Collection ID: 5iwFavPxXKvnSoyPWHzYB6F5EfbvQq6U3jrS7GXUs3EA
Update Authority: AxVR1S5Wzp74YfzDYespasU5cgjjemR33uMsaQF2Tp7H

Please let me know how to proceed.

**Comment by samuelvanderwaal** [comment]
Your update authority `AxVR1S5Wzp74YfzDYespasU5cgjjemR33uMsaQF2Tp7H` does not match that stored on the migration state `2nGSfCTTZFLo2D2Tc1E9cmc18dLE3hjECYY5a3mZUQWw,` and that is likely why the migration is failing. You must have changed the updated authority on your collection after starting the migration a few weeks back? You can change the update authority on the migration state by using the old one as the signing keypair and running [goose update](https://github.com/metaplex-foundation/goose):

```bash
goose update -k <old-keypair.json> -c 5iwFavPxXKvnSoyPWHzYB6F5EfbvQq6U3jrS7GXUs3EA -n AxVR1S5Wzp74YfzDYespasU5cgjjemR33uMsaQF2Tp7H
```
